use syn::ItemFn;

/// Determines if this block of code was generated by near_bindgen.
/// Heuristic used is to check for #[no_mangle].
/// TODO: How to make this 100% safe. Discuss with near-sdk team
pub(crate) fn is_near_bindgen_wrapped_code(item: &ItemFn) -> bool {
    let pattern = "(target_arch = \"wasm32\")";
    item.attrs
        .iter()
        .any(|attr| attr.tokens.to_string() == pattern)
}
