---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: near-plugins-examples
  description: |-
    Aurora Engine Tests
  tags:
    - near
  links: []
  annotations:
    aurora.dev/security-tier: "-1"
spec:
  owner: protocol-team
  type: contract-examples
  lifecycle: production
  system: near-plugins
  interactsWith: []
