name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - master

env:
  RELEASE_PLZ_VERSION: "0.3.157"
  RUST_TOOLCHAIN_VERSION: "1.86"

jobs:
  # Create a PR with the new versions and changelog, preparing the next release.
  release-plz-pr:
    name: Release-plz PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency: 
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
          targets: wasm32-unknown-unknown

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1

      - name: Install cargo-semver-checks
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-semver-checks@0.46

      - name: Install release-plz
        run: cargo-binstall release-plz@${{ env.RELEASE_PLZ_VERSION }} --force --no-confirm

      - name: Configure git user
        uses: release-plz/git-config@v1

      - name: Run release-plz release-pr
        run: release-plz release-pr --git-token "$GITHUB_TOKEN" --repo-url "https://github.com/$GITHUB_REPOSITORY" -o json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          CARGO_BUILD_TARGET: wasm32-unknown-unknown

  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    needs: release-plz-pr
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
          targets: wasm32-unknown-unknown

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1

      - name: Install release-plz
        run: cargo-binstall release-plz@${{ env.RELEASE_PLZ_VERSION }} --force --no-confirm

      - name: Configure git user
        uses: release-plz/git-config@v1

      - name: Run release-plz release
        run: release-plz release --git-token "$GITHUB_TOKEN" -o json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          CARGO_BUILD_TARGET: wasm32-unknown-unknown
