---
name: "Contract Security Analysis"

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "30 15 * * *"
  workflow_dispatch:

jobs:
  contract_analysis:
    name: "Shared"
    uses: aurora-is-near/.github/.github/workflows/security_analysis.yml@feat/datadog-metrics
    secrets: inherit
