name: Rust Contracts

on:
  push:
    branches:
      - master
  pull_request:

env:
  RUST_BACKTRACE: full
  MSRV: 1.86.0

jobs:
  tests:
    name: Tests
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust ${{ env.MSRV }} with wasm32 target
        run: |
          rustup toolchain install ${{ env.MSRV }} --profile minimal --target wasm32-unknown-unknown
          rustup override set ${{ env.MSRV }}

      - uses: Swatinem/rust-cache@v2
        with:
          cache-provider: warpbuild
          shared-key: "linux-${{ env.MSRV }}-test"
          cache-all-crates: true

      - name: cargo test
        run: cargo test --all-features

  lint:
    name: Format and Clippy
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust ${{ env.MSRV }} with wasm32 target and components
        run: |
          rustup toolchain install ${{ env.MSRV }} --profile minimal --target wasm32-unknown-unknown --component rustfmt,clippy
          rustup override set ${{ env.MSRV }}

      - uses: Swatinem/rust-cache@v2
        with:
          cache-provider: warpbuild
          shared-key: "linux-${{ env.MSRV }}-lint"
          cache-all-crates: true

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy --all-features --all-targets -- -D warnings
